// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaucyBot.Database;

#nullable disable

namespace SaucyBot.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260831085858_AddUuidIdToGuildConfiguration")]
    partial class AddUuidIdToGuildConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SaucyBot.Database.Models.GuildConfiguration", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("guild_id");

                    b.Property<uint>("MaximumArtStationImages")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_art_station_images");

                    b.Property<uint>("MaximumEmbeds")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_embeds");

                    b.Property<uint>("MaximumPixivImages")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_pixiv_images");

                    b.Property<bool>("RestrictToRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("restrict_to_roles");

                    b.Property<bool>("SendMatchedMessage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("send_matched_message");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guild_configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
