// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaucyBot.Database;

#nullable disable

namespace SaucyBot.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260901085858_AddRestrictedRoleTable")]
    partial class AddRestrictedRoleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SaucyBot.Database.Models.GuildConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("guild_id");

                    b.Property<uint>("MaximumArtStationImages")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_art_station_images");

                    b.Property<uint>("MaximumEmbeds")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_embeds");

                    b.Property<uint>("MaximumPixivImages")
                        .HasColumnType("int unsigned")
                        .HasColumnName("maximum_pixiv_images");

                    b.Property<bool>("RestrictToRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("restrict_to_roles");

                    b.Property<bool>("SendMatchedMessage")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("send_matched_message");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guild_configurations");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_configurations_guild_id");

                    b.ToTable("guild_configurations", (string)null);
                });

            modelBuilder.Entity("SaucyBot.Database.Models.GuildConfigurationRestrictedRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuildConfigurationId")
                        .HasColumnType("uuid")
                        .HasColumnName("guild_configuration_id")
                        .IsFixedLength(false);

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guild_configuration_restricted_roles");

                    b.HasIndex("GuildConfigurationId")
                        .HasDatabaseName("ix_guild_configuration_restricted_roles_guild_configuration_id");

                    b.HasIndex("GuildConfigurationId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_guild_configuration_restricted_roles_guild_configuration_id_");

                    b.ToTable("guild_configuration_restricted_roles", (string)null);
                });

            modelBuilder.Entity("SaucyBot.Database.Models.GuildConfigurationRestrictedRole", b =>
                {
                    b.HasOne("SaucyBot.Database.Models.GuildConfiguration", "GuildConfiguration")
                        .WithMany("RestrictedRoles")
                        .HasForeignKey("GuildConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_configuration_restricted_roles_guild_configurations_gu");

                    b.Navigation("GuildConfiguration");
                });

            modelBuilder.Entity("SaucyBot.Database.Models.GuildConfiguration", b =>
                {
                    b.Navigation("RestrictedRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
