services:
  bot:
    build:
      dockerfile: Containerfile
      context: .
      args:
        CONFIGURATION: '${CONFIGURATION}'
    env_file:
      - .env
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mariadb:12.3@sha256:a02fe89cb597d4375812b2eac90cf9d0775d4686daa7f7cc750ebbcad7525bbc
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: 'valkey/valkey:9-alpine@sha256:ee91f7a174ac4d6a6b0685b3a60e321f0a9dbbb691f9b0e285be2ba1d1be8328'
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    restart: unless-stopped
    healthcheck:
      test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
      timeout: 30s
      retries: 10
      start_period: 10s

volumes:
  database:
  cache:
