services:
  bot:
    build:
      dockerfile: Containerfile
      context: .
      args:
        CONFIGURATION: '${CONFIGURATION}'
    env_file:
      - .env
    volumes:
      - ./appsettings.Development.json:/app/appsettings.Development.json
    depends_on:
      cache:
        condition: service_healthy
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mariadb:12.3@sha256:c237fd50cc48d6f2b87c4ca66d52f3b5eef7271b3bea7aee586c0be19d5b460d
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: 'valkey/valkey:9-alpine@sha256:de31910896150d5e754a07d57d227cfdde4e258ddd0d1aa4607f2d2f95843715'
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    restart: unless-stopped
    healthcheck:
      test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
      timeout: 30s
      retries: 10
      start_period: 10s

volumes:
  database:
  cache:
