ARG CONFIGURATION=Release

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0-alpine3.24@sha256:979da27fc87dc255f4675b7642556cdcba9307459f8891f85f3cc26edcd7e766 AS build

ENV HUSKY=0

WORKDIR /src

COPY ["SaucyBot.csproj", "packages.lock.json", "SaucyBot/"]

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/http-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugin-cache \
    --mount=type=cache,target=/tmp/NuGetScratchs \
    dotnet restore "SaucyBot/SaucyBot.csproj" -a "${TARGETARCH}" -restoreProperty:RestoreLockedMode=true

COPY . SaucyBot/

WORKDIR /src/SaucyBot

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet build "SaucyBot.csproj" -c "${CONFIGURATION}" -a "${TARGETARCH}" -o /app/build

FROM build AS publish

RUN dotnet publish "SaucyBot.csproj" -c "${CONFIGURATION}" -a "${TARGETARCH}" -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0-alpine3.24-extra@sha256:121d26e898168524cf5c0ee163356ae9d22654df368dc0b5cd4efa2176a8b422 AS final

WORKDIR /app

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

RUN set -xe; \
    apk add --no-cache --update \
        ffmpeg=8.1.2-r0

COPY --from=publish /app/publish .

USER "${APP_UID}"

ENTRYPOINT ["dotnet", "SaucyBot.dll"]
