ARG CONFIGURATION=Release

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:11.0-alpine3.24@sha256:a7738e8663d6b128c08df945169d9072a9ea49f8b97de76befe0388741287925 AS build

ENV HUSKY=0

WORKDIR /src

COPY ["SaucyBot.csproj", "packages.lock.json", "SaucyBot/"]

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    --mount=type=cache,target=/root/.local/share/NuGet/http-cache \
    --mount=type=cache,target=/root/.local/share/NuGet/plugin-cache \
    --mount=type=cache,target=/tmp/NuGetScratchs \
    dotnet restore "SaucyBot/SaucyBot.csproj" -a "${TARGETARCH}" -restoreProperty:RestoreLockedMode=true

COPY . SaucyBot/

WORKDIR /src/SaucyBot

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet build "SaucyBot.csproj" -c "${CONFIGURATION}" -a "${TARGETARCH}" -o /app/build

FROM build AS publish

RUN dotnet publish "SaucyBot.csproj" -c "${CONFIGURATION}" -a "${TARGETARCH}" -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:11.0-alpine3.24-extra@sha256:131f8d5ebe108424b6825cd01b8719ee9607f7bf6af2154e0be39ec03c304b65 AS final

WORKDIR /app

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

RUN set -xe; \
    apk add --no-cache --update \
        ffmpeg=8.1.2-r0

COPY --from=publish /app/publish .

USER "${APP_UID}"

ENTRYPOINT ["dotnet", "SaucyBot.dll"]
