services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.Development.json:/app/appsettings.Development.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:272084c2dec70619714df329c4ffcb336e3f8c723072c3f56f2e4015997bbf2c
        env_file:
            - .env
        ports:
            - "3306:3306"
        restart: unless-stopped
        healthcheck:
            test: 'mariadb-admin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 30s
            retries: 10
            start_period: 10s
        
    cache:
        image: "valkey/valkey:8-alpine@sha256:9c3e63b9b6ba69f2fe5d4e32dd8c0e2be3b3e9cbee3940c0cde6a884d55a303a"
        ports:
            - "6379:6379"
        restart: unless-stopped
        healthcheck:
            test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s
