services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.Development.json:/app/appsettings.Development.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:12.3
        env_file:
            - .env
        ports:
            - "3306:3306"
        restart: unless-stopped
        healthcheck:
            test: 'mariadb-admin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 30s
            retries: 10
            start_period: 10s
        
    cache:
        image: "valkey/valkey:9-alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5"
        ports:
            - "6379:6379"
        restart: unless-stopped
        healthcheck:
            test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s
