services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "Release"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:11706a6fd276c2eada52d0d69b1a2aa1f1484cbe78137678e02cca8f7a0ae502
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 20s
            retries: 10
        
    cache:
        image: "valkey/valkey:8-alpine@sha256:f43639a6811342b5db26475f3463d4d1950d07bf05542d9483159a44be1fe62f"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        restart: unless-stopped
        healthcheck:
            test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s

volumes: 
    cache:
    database:
