services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "Release"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:1e4ec03d1b73af8e7a63137b8ef4820ac7d54c654a1e99eb76235f210f7f0a06
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 20s
            retries: 10
        
    cache:
        image: "valkey/valkey:8-alpine@sha256:81681ebc32ea2ce5153094084ca541861168ff588b4b0db998046fc896b99ba7"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        restart: unless-stopped
        healthcheck:
            test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s

volumes: 
    cache:
    database:
