services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "Release"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:11@sha256:ec5d50f32359ff020b93cce6834f9bf89147c34aea0e90c952ccf556c94a4fb8
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: 'mysqladmin ping -h 127.0.0.1 -u "$MYSQL_USER" --password="$MYSQL_PASSWORD"'
            timeout: 20s
            retries: 10
        
    cache:
        image: "valkey/valkey:8-alpine@sha256:9c3e63b9b6ba69f2fe5d4e32dd8c0e2be3b3e9cbee3940c0cde6a884d55a303a"
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        restart: unless-stopped
        healthcheck:
            test: '[ $(valkey-cli -h 127.0.0.1 ping) = "PONG" ]'
            timeout: 30s
            retries: 10
            start_period: 10s

volumes: 
    cache:
    database:
