name: 'Build Container'

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push to container registry'
        required: false
        type: boolean
        default: false
      configuration:
        description: '.NET build configuration'
        required: false
        type: string
        default: 'Release'
      tags:
        description: 'Docker image tags'
        required: false
        type: string
        default: ''
      labels:
        description: 'Docker image labels'
        required: false
        type: string
        default: ''

env:
  HUSKY: 0
  DOTNET_VERSION: '10.x'

jobs:
  build:
    name: 'Build'
    runs-on: 'ubuntu-24.04'

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: 'Setup QEMU'
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: 'Setup Buildx'
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: 'Login to Container Registry'
        if: ${{ inputs.push && github.event_name == 'release' }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: 'Build and Push'
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          push: ${{ inputs.push && github.event_name == 'release' }}
          file: ./SaucyBot/Containerfile
          context: ./SaucyBot
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CONFIGURATION=${{ inputs.configuration }}
