name: 'Continuous Integration'

on:
  workflow_dispatch:
  push:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.slnx'
      - '**/Containerfile'
      - '**/Containerfile.*'
      - '**/Dockerfile'
      - '**/Dockerfile.*'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.slnx'
      - '**/Containerfile'
      - '**/Containerfile.*'
      - '**/Dockerfile'
      - '**/Dockerfile.*'

permissions:
  contents: read
  pull-requests: write

env:
  DOTNET_VERSION: '10.x'
  HUSKY: 0

jobs:
  build:
    name: 'Build and Test'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: arm64
            os: ubuntu-24.04-arm

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: 'Setup .NET Core SDK ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: 'SaucyBot/packages.lock.json'

      - name: 'Lint'
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic

      - name: 'Install Dependencies'
        run: |
          dotnet restore -a ${{ matrix.arch }} -restoreProperty:RestoreLockedMode=true

      - name: 'Build'
        run: |
          dotnet build --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test --no-restore --verbosity normal

  container:
    name: 'Build Container'
    uses: ./.github/workflows/build-container.yml
