name: 'Production Continuous Deployment'

on:
  release:
    types: [released]

jobs:
  package:
    name: 'Publish Container'
    runs-on: ubuntu-latest
    steps:
      # Setup working environment for Docker
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - id: docker_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/sn0wcrack/saucybot-discord
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
      - name: 'Login to Container Registry'
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: 'Build and Publish'
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
          CONFIGURATION: Release
        with:
          push: true
          context: ./SaucyBot
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: CONFIGURATION=Release
          
  deploy:
    name: 'Deploy'
    needs: package
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - uses: appleboy/ssh-action@823bd89e131d8d508129f9443cad5855e9ba96f0 # v1.2.4
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./update.sh
