name: 'Production Continuous Deployment'

on:
  release:
    types: [released]

permissions:
  contents: read

env:
  DOTNET_VERSION: '10.x'
  HUSKY: 0

jobs:
  metadata:
    name: 'Generate Metadata'
    runs-on: 'ubuntu-24.04'
    outputs:
      tags: ${{ steps.docker_meta.outputs.tags }}
      labels: ${{ steps.docker_meta.outputs.labels }}
    steps:
      - name: 'Generate Docker Tags and Metadata'
        id: docker_meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: ghcr.io/sn0wcrack/saucybot-discord
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

  package:
    name: 'Publish Container'
    needs: metadata
    uses: ./.github/workflows/build-container.yml
    with:
      push: true
      tags: ${{ needs.metadata.outputs.tags }}
      labels: ${{ needs.metadata.outputs.labels }}
    permissions:
      packages: write
      contents: read

  deploy:
    name: 'Deploy'
    needs: package
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: 'Deploy'
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./update.sh
