name: 'Continuous Integration'

on:
  workflow_dispatch:
  push:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
    tags-ignore:
      - 'v*'
  pull_request:
    branches: ['v2']
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build:
    name: 'Build and Test'
    continue-on-error: true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['10.x']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.dotnet-version }}-nuget

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
